package delivery.api;

import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;

/**
 * Toy PresenceDetectorThing API
 *
 *
 */
public interface PresenceDetectorThingAPI {
	
	/**
	 * Get the TD
	 * 
	 * @return
	 */
	Future<JsonObject> getTD();
	
	/* properties */

	/**
	 *
	 * Get the presence or not
	 *
	 */
	Future<Boolean> presenceDetected();
	
	/* actions */

	/**
	 * Subscribe to events generated by the presence detector
	 * 
	 * @param handler
	 * @return
	 */
	Future<Void> subscribe(Handler<JsonObject> handler);
}
