package presenceDetector_thing.api;

import io.vertx.core.Future;
import io.vertx.core.Handler;
import io.vertx.core.json.JsonObject;

/**
 * Toy PresenceDetectorThing API
 *
 *
 */
public interface PresenceDetectorThingAPI {
	
	/**
	 * Get the TD
	 * 
	 * @return
	 */
	Future<JsonObject> getTD();
	
	/* properties */

	/**
	 * 
	 * Get the state of the Detector
	 * 
	 */
	Future<String> getState();
	
	/* actions */

	/**
	 * 
	 * Start detection
	 * 
	 * @return
	 */
	Future<Void> startDetection();


	/**
	 * Subscribe to events generated by the presence detector
	 * 
	 * @param handler
	 * @return
	 */
	Future<Void> subscribe(Handler<JsonObject> handler);
}
